import { v2 as cloudinary, type UploadApiResponse, type UploadApiErrorResponse } from 'cloudinary';
import type { StorageProvider, UploadOptions, UploadResult } from './types.js';

export interface CloudinaryConfig {
  cloudName: string;
  apiKey: string;
  apiSecret: string;
  /** Default upload folder — overridable per-call via UploadOptions.folder */
  folder?: string;
}

/**
 * Cloudinary storage provider.
 *
 * Objects are uploaded to `<folder>/<auto-generated-public-id>` and served
 * via Cloudinary's CDN.  The `key` stored in the database is Cloudinary's
 * `public_id` (which includes the folder prefix), used for deletion and
 * on-demand URL generation.
 *
 * Cloudinary free tier limitations (as of 2024):
 *   25 credits / month, 25 GB storage, 25 GB bandwidth.
 * Check https://cloudinary.com/pricing for current limits before going live.
 */
export class CloudinaryStorageProvider implements StorageProvider {
  private readonly defaultFolder: string;

  constructor(cfg: CloudinaryConfig) {
    cloudinary.config({
      cloud_name: cfg.cloudName,
      api_key:    cfg.apiKey,
      api_secret: cfg.apiSecret,
    });
    this.defaultFolder = cfg.folder ?? 'device-images';
  }

  async upload(
    buffer: Buffer,
    { folder, mimeType }: UploadOptions,
  ): Promise<UploadResult> {
    const result = await new Promise<UploadApiResponse>((resolve, reject) => {
      cloudinary.uploader
        .upload_stream(
          { folder: folder ?? this.defaultFolder, resource_type: 'image' },
          (err: UploadApiErrorResponse | undefined, res: UploadApiResponse | undefined) =>
          err ? reject(err) : resolve(res!),
        )
        .end(buffer);
    });

    return {
      key:      result.public_id,   // e.g. 'device-images/abc123'
      url:      result.secure_url,  // Cloudinary CDN HTTPS URL
      size:     result.bytes,
      mimeType,
    };
  }

  async delete(key: string): Promise<void> {
    await cloudinary.uploader.destroy(key).catch(() => {});
  }

  getUrl(key: string): string {
    // Re-derive the CDN URL from the public_id (secure by default)
    return cloudinary.url(key, { secure: true });
  }
}
